### ISSUE TITLE
百度指数的按照时间来选择是怎么做的

### ISSUE THREAD

**Issue by zw231212** [TTyb/Baiduindex#1]
我把输入的js信息改成了如下的xi形式：

`days = "-".join(str(day).split(","))`
`params = {'time':days,'word':keyword}`
`querystring = urlencode(params)`
`print (querystring)`
`url = 'http://index.baidu.com/?tpl=trend&type=0&area=0&'+querystring`
`url.replace("-","%7C")`
`print(url)`
` js = 'window.open("'+url+'");'`
`browser.execute_script(js)`

在模拟的浏览器上就成了：（图片上传不了），就是在地址栏里面word后面是中文，而不是urlencode后的字符，而且在输入框里面的是乱码。

请问：有什么比较不麻烦的时间选择特定时间获取数据的方式么，操作选择框，填充时间这个我没有尝试成功。

**Comment by TTyb** [comment]
我在网页里面选择时间只有7\30\90\半年\全部这几个选项，选择时间的时候只是js改变了图形，网址没有任何的变化，说明这里只是js的变化，而网页没有get和post，这也就说明一开始7\30\90\半年\全部这几个选项的数据就加载好了，你需要做的只是去破译js

**Comment by hello-world-wanghui** [comment]
我实现的方法是用js语句修改 7/30/90/半年/全部/  这里里面任意一个标签的 rel 值 比如修改为360 那么就会取得前一年的数据
